import Config

# Base de datos: en Docker se usa DATABASE_URL (servicio `db`); fuera de Docker, localhost.
if database_url = System.get_env("DATABASE_URL") do
  config :eth, Eth.Repo, url: database_url
else
  config :eth, Eth.Repo,
    username: "postgres",
    password: "postgres",
    hostname: "localhost",
    database: "eth_dev"
end

config :eth, Eth.Repo,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# IP de escucha: loopback por defecto (RNF-4.5); dentro del contenedor PHX_BIND=0.0.0.0
# y docker-compose publica el puerto solo en 127.0.0.1 del host (RNF-11.4).
bind_ip =
  case System.get_env("PHX_BIND", "127.0.0.1")
       |> String.split(".")
       |> Enum.map(&Integer.parse/1) do
    [{a, ""}, {b, ""}, {c, ""}, {d, ""}] -> {a, b, c, d}
    _ -> raise "PHX_BIND inválido: se espera una IPv4 como 0.0.0.0"
  end

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :eth, EthWeb.Endpoint,
  http: [ip: bind_ip],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "zWE+iLCkNkMAe6LU5csVmoSoRkQA8UvL9T6s+7V1o/ETB5Li1mo1ApAydDW1NT/m",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:eth, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:eth, ~w(--watch)]}
  ]

# Código en NTFS montado en Docker: no llegan eventos inotify al contenedor (RNF-11.2).
# Con ETH_FS_POLL=true el live reload y el watcher de Tailwind usan polling.
# (esbuild --watch ya funciona por polling y el code reloader usa mtimes.)
if System.get_env("ETH_FS_POLL") == "true" do
  # Solo los directorios que importan: recorrer _build/ y deps/ por polling es lento
  # y falla con el symlink colgante _build/dev/phoenix-colocated/*/node_modules.
  config :phoenix_live_reload,
    backend: :fs_poll,
    backend_opts: [interval: 500],
    dirs: ["lib", "priv/static", "priv/gettext"]

  config :eth, EthWeb.Endpoint,
    watchers: [
      esbuild: {Esbuild, :install_and_run, [:eth, ~w(--sourcemap=inline --watch)]},
      tailwind: {Eth.Dev.TailwindPoller, :run, [:eth]}
    ]
end

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :eth, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
