import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :eth, EthWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Sin force_ssl: la aplicación corre en la máquina del piloto por HTTP, publicada solo en
# 127.0.0.1 (D-20, RNF-4.5); no hay certificado ni proxy delante.

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
